sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    # - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 6

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

install:
  - 'echo "{ \"key\": \"${GIPHY_API_KEY}\" }" > config.json'
  - nvm install 6
  - npm install

script:
  - npm run test

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build'
